# [[file:lbfgsb.note::56fdcc09][56fdcc09]]
[package]
name = "lbfgsb"
edition = "2021"
version = "0.1.0"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
anyhow = "1"

[build-dependencies]
cc = "1"
bindgen = "0.65.1"

[dev-dependencies]
vecfx = { version = "0.1" }
# 56fdcc09 ends here
